# Evaluate the Finetune Results

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import os
import dict_dtype, utils

import importlib

importlib.reload(dict_dtype)
importlib.reload(utils)

In [2]:
from pandas import factorize

In [3]:
pd.set_option('display.max_rows', None) # show all
pd.reset_option('display.max_rows') # undo

## Load csv

In [4]:
dir_csv_main = '../finetune/evaluations'
list_sub_dir = sorted([d for d in os.listdir(dir_csv_main) if os.path.isdir(os.path.join(dir_csv_main, d)) and "ft_version" in d])

print(list_sub_dir)
list_csv = sorted([f for f in os.listdir(f"{dir_csv_main}/{list_sub_dir[0]}") if f.endswith('.csv')])
list_csv

['ft_version_0', 'ft_version_1', 'ft_version_2', 'ft_version_3', 'ft_version_4']

['ChemBart_Medium_10m.csv',
 'ChemBart_Medium_20m.csv',
 'ChemBart_Medium_30m.csv',
 'ChemBart_Small_10m.csv',
 'ChemBart_Small_20m.csv',
 'ChemBart_Small_30m.csv',
 'ChemBerta_Medium_10m.csv',
 'ChemBerta_Medium_20m.csv',
 'ChemBerta_Medium_30m.csv',
 'ChemBerta_Small_10m.csv',
 'ChemBerta_Small_20m.csv',
 'ChemBerta_Small_30m.csv',
 'ChemLlama_Medium_10m.csv',
 'ChemLlama_Medium_20m.csv',
 'ChemLlama_Medium_30m.csv',
 'ChemLlama_Small_10m.csv',
 'ChemLlama_Small_20m.csv',
 'ChemLlama_Small_30m.csv']

In [5]:
list_df = list()
for ver, local_sub_dir in enumerate(list_sub_dir):
    for local_csv in list_csv:
        local_df = pd.read_csv(f"{dir_csv_main}/{local_sub_dir}/{local_csv}")
        local_df.insert(loc=0, column='ft_version', value=[ver]*local_df.shape[0])
        list_df.append(local_df)

list_df

[     ft_version       model_mtr_name  model_mtr_ep         dataset_name  \
 0             0  ChemBart_Medium_10m           0.0  bace_classification
 1             0  ChemBart_Medium_10m           0.0  bace_classification
 2             0  ChemBart_Medium_10m           0.0  bace_classification
 3             0  ChemBart_Medium_10m           0.0  bace_classification
 4             0  ChemBart_Medium_10m           0.0  bace_classification
 ..          ...                  ...           ...                  ...
 289           0  ChemBart_Medium_10m           6.0         tox21_sr_p53
 290           0  ChemBart_Medium_10m           6.0         tox21_sr_p53
 291           0  ChemBart_Medium_10m           6.0         tox21_sr_p53
 292           0  ChemBart_Medium_10m           6.0         tox21_sr_p53
 293           0  ChemBart_Medium_10m           6.0         tox21_sr_p53

        dataset_type  metric_1  metric_2  p_value_mantissa  p_value_exponent  \
 0    classification  0.648188       NaN          0.001820               NaN
 1    classification  0.760688       NaN          1.253343              -8.0
 2    classification  0.805435       NaN          8.985626             -12.0
 3    classification  0.800000       NaN          2.386729             -11.0
 4    classification  0.808333       NaN          5.272629             -12.0
 ..              ...       ...       ...               ...               ...
 289  classification  0.766727       NaN          1.207529              -9.0
 290  classification  0.790002       NaN          3.490191             -11.0
 291  classification  0.793039       NaN          2.147288             -11.0
 292  classification  0.799865       NaN          7.064837             -12.0
 293  classification  0.801519       NaN          5.374221             -12.0

      epoch      loss  loss_ranking  metric_1_ranking
 0        0  0.993232             6                 6
 1        1  0.717989             5                 5
 2        2  0.650228             0                 3
 3        3  0.651059             1                 4
 4        4  0.660707             2                 1
 ..     ...       ...           ...               ...
 289      2  0.169661             4                 5
 290      3  0.164469             1                 3
 291      4  0.163425             0                 2
 292      5  0.166083             2                 1
 293      6  0.166461             3                 0

 [294 rows x 13 columns],
      ft_version       model_mtr_name  model_mtr_ep         dataset_name  \
 0             0  ChemBart_Medium_20m           0.0  bace_classification
 1             0  ChemBart_Medium_20m           0.0  bace_classification
 2             0  ChemBart_Medium_20m           0.0  bace_classification
 3             0  ChemBart_Medium_20m           0.0  bace_classification
 4             0  ChemBart_Medium_20m           0.0  bace_classification
 ..          ...                  ...           ...                  ...
 289           0  ChemBart_Medium_20m           6.0         tox21_sr_p53
 290           0  ChemBart_Medium_20m           6.0         tox21_sr_p53
 291           0  ChemBart_Medium_20m           6.0         tox21_sr_p53
 292           0  ChemBart_Medium_20m           6.0         tox21_sr_p53
 293           0  ChemBart_Medium_20m           6.0         tox21_sr_p53

        dataset_type  metric_1  metric_2  p_value_mantissa  p_value_exponent  \
 0    classification  0.644746       NaN          0.002340               NaN
 1    classification  0.770833       NaN          2.824376              -9.0
 2    classification  0.771377       NaN          2.601555              -9.0
 3    classification  0.791667       NaN          1.009758             -10.0
 4    classification  0.771196       NaN          2.673876              -9.0
 ..              ...       ...       ...               ...               ...
 289  classification  0.747692       NaN          1.739436              -8.0
 290  classification  0.804526       NaN          3.254770             -12.0
 291  classification  0.807713       NaN          1.901452             -12.0
 292  classification  0.816644       NaN          4.081621             -13.0
 293  classification  0.816915       NaN          3.892729             -13.0

      epoch      loss  loss_ranking  metric_1_ranking
 0        0  1.020729             6                 6
 1        1  0.755936             5                 5
 2        2  0.728258             2                 3
 3        3  0.712370             0                 0
 4        4  0.716102             1                 4
 ..     ...       ...           ...               ...
 289      2  0.166263             1                 5
 290      3  0.168259             2                 3
 291      4  0.162714             0                 2
 292      5  0.172644             5                 1
 293      6  0.171900             4                 0

 [294 rows x 13 columns],
      ft_version       model_mtr_name  model_mtr_ep         dataset_name  \
 0             0  ChemBart_Medium_30m           0.0  bace_classification
 1             0  ChemBart_Medium_30m           0.0  bace_classification
 2             0  ChemBart_Medium_30m           0.0  bace_classification
 3             0  ChemBart_Medium_30m           0.0  bace_classification
 4             0  ChemBart_Medium_30m           0.0  bace_classification
 ..          ...                  ...           ...                  ...
 289           0  ChemBart_Medium_30m           6.0         tox21_sr_p53
 290           0  ChemBart_Medium_30m           6.0         tox21_sr_p53
 291           0  ChemBart_Medium_30m           6.0         tox21_sr_p53
 292           0  ChemBart_Medium_30m           6.0         tox21_sr_p53
 293           0  ChemBart_Medium_30m           6.0         tox21_sr_p53

        dataset_type  metric_1  metric_2  p_value_mantissa  p_value_exponent  \
 0    classification  0.617754       NaN          0.013789               NaN
 1    classification  0.783877       NaN          3.668580             -10.0
 2    classification  0.801630       NaN          1.785898             -11.0
 3    classification  0.796739       NaN          4.229962             -11.0
 4    classification  0.798732       NaN          2.985273             -11.0
 ..              ...       ...       ...               ...               ...
 289  classification  0.729349       NaN          1.877551              -7.0
 290  classification  0.792167       NaN          2.470043             -11.0
 291  classification  0.793099       NaN          2.126616             -11.0
 292  classification  0.796587       NaN          1.208995             -11.0
 293  classification  0.796226       NaN          1.282159             -11.0

      epoch      loss  loss_ranking  metric_1_ranking
 0        0  1.025761             6                 6
 1        1  0.784096             5                 5
 2        2  0.722256             0                 2
 3        3  0.751228             2                 4
 4        4  0.745151             1                 3
 ..     ...       ...           ...               ...
 289      2  0.164291             2                 6
 290      3  0.165650             4                 3
 291      4  0.161836             0                 2
 292      5  0.164911             3                 0
 293      6  0.162738             1                 1

 [294 rows x 13 columns],
      ft_version      model_mtr_name  model_mtr_ep         dataset_name  \
 0             0  ChemBart_Small_10m           0.0  bace_classification
 1             0  ChemBart_Small_10m           0.0  bace_classification
 2             0  ChemBart_Small_10m           0.0  bace_classification
 3             0  ChemBart_Small_10m           0.0  bace_classification
 4             0  ChemBart_Small_10m           0.0  bace_classification
 ..          ...                 ...           ...                  ...
 289           0  ChemBart_Small_10m           6.0         tox21_sr_p53
 290           0  ChemBart_Small_10m           6.0         tox21_sr_p53
 291           0  ChemBart_Small_10m           6.0         tox21_sr_p53
 292           0  ChemBart_Small_10m           6.0         tox21_sr_p53
 293           0  ChemBart_Small_10m           6.0         tox21_sr_p53

        dataset_type  metric_1  metric_2  p_value_mantissa  p_value_exponent  \
 0    classification  0.768116       NaN          4.244165              -9.0
 1    classification  0.772101       NaN          2.330678              -9.0
 2    classification  0.820652       NaN          4.959859             -13.0
 3    classification  0.798551       NaN          3.081853             -11.0
 4    classification  0.809964       NaN          3.891860             -12.0
 ..              ...       ...       ...               ...               ...
 289  classification  0.774335       NaN          3.924733             -10.0
 290  classification  0.794001       NaN          1.838902             -11.0
 291  classification  0.809187       NaN          1.480059             -12.0
 292  classification  0.805638       NaN          2.699850             -12.0
 293  classification  0.804014       NaN          3.545777             -12.0

      epoch      loss  loss_ranking  metric_1_ranking
 0        0  0.750152             6                 6
 1        1  0.722967             5                 5
 2        2  0.673664             2                 0
 3        3  0.695253             4                 4
 4        4  0.670187             1                 2
 ..     ...       ...           ...               ...
 289      2  0.161743             1                 5
 290      3  0.163594             2                 3
 291      4  0.161702             0                 0
 292      5  0.166336             3                 1
 293      6  0.166470             4                 2

 [294 rows x 13 columns],
      ft_version      model_mtr_name  model_mtr_ep         dataset_name  \
 0             0  ChemBart_Small_20m           0.0  bace_classification
 1             0  ChemBart_Small_20m           0.0  bace_classification
 2             0  ChemBart_Small_20m           0.0  bace_classification
 3             0  ChemBart_Small_20m           0.0  bace_classification
 4             0  ChemBart_Small_20m           0.0  bace_classification
 ..          ...                 ...           ...                  ...
 289           0  ChemBart_Small_20m           6.0         tox21_sr_p53
 290           0  ChemBart_Small_20m           6.0         tox21_sr_p53
 291           0  ChemBart_Small_20m           6.0         tox21_sr_p53
 292           0  ChemBart_Small_20m           6.0         tox21_sr_p53
 293           0  ChemBart_Small_20m           6.0         tox21_sr_p53

        dataset_type  metric_1  metric_2  p_value_mantissa  p_value_exponent  \
 0    classification  0.788587       NaN          1.692694               -10
 1    classification  0.794746       NaN          5.970949               -11
 2    classification  0.826993       NaN          1.376925               -13
 3    classification  0.800362       NaN          2.238270               -11
 4    classification  0.821920       NaN          3.852446               -13
 ..              ...       ...       ...               ...               ...
 289  classification  0.768381       NaN          9.484589               -10
 290  classification  0.776169       NaN          2.978268               -10
 291  classification  0.803263       NaN          4.020506               -12
 292  classification  0.807412       NaN          2.000879               -12
 293  classification  0.804255       NaN          3.405793               -12

      epoch      loss  loss_ranking  metric_1_ranking
 0        0  0.723317             2                 6
 1        1  0.740623             6                 5
 2        2  0.701404             0                 0
 3        3  0.733798             5                 4
 4        4  0.727645             3                 1
 ..     ...       ...           ...               ...
 289      2  0.171219             3                 4
 290      3  0.166485             1                 3
 291      4  0.164948             0                 2
 292      5  0.171324             4                 0
 293      6  0.172929             5                 1

 [294 rows x 13 columns],
      ft_version      model_mtr_name  model_mtr_ep         dataset_name  \
 0             0  ChemBart_Small_30m           0.0  bace_classification
 1             0  ChemBart_Small_30m           0.0  bace_classification
 2             0  ChemBart_Small_30m           0.0  bace_classification
 3             0  ChemBart_Small_30m           0.0  bace_classification
 4             0  ChemBart_Small_30m           0.0  bace_classification
 ..          ...                 ...           ...                  ...
 289           0  ChemBart_Small_30m           6.0         tox21_sr_p53
 290           0  ChemBart_Small_30m           6.0         tox21_sr_p53
 291           0  ChemBart_Small_30m           6.0         tox21_sr_p53
 292           0  ChemBart_Small_30m           6.0         tox21_sr_p53
 293           0  ChemBart_Small_30m           6.0         tox21_sr_p53

        dataset_type  metric_1  metric_2  p_value_mantissa  p_value_exponent  \
 0    classification  0.765217       NaN          6.510083                -9
 1    classification  0.785870       NaN          2.651136               -10
 2    classification  0.778080       NaN          9.252458               -10
 3    classification  0.764493       NaN          7.237321                -9
 4    classification  0.785870       NaN          2.651136               -10
 ..              ...       ...       ...               ...               ...
 289  classification  0.769433       NaN          8.126870               -10
 290  classification  0.786874       NaN          5.722823               -11
 291  classification  0.812224       NaN          8.794436               -13
 292  classification  0.812314       NaN          8.658764               -13
 293  classification  0.814299       NaN          6.142824               -13

      epoch      loss  loss_ranking  metric_1_ranking
 0        0  0.734773             2                 5
 1        1  0.715758             1                 2
 2        2  0.687578             0                 4
 3        3  0.752276             3                 6
 4        4  0.763620             5                 2
 ..     ...       ...           ...               ...
 289      2  0.171336             2                 4
 290      3  0.175654             4                 3
 291      4  0.166795             0                 2
 292      5  0.175610             3                 1
 293      6  0.175913             5                 0

 [294 rows x 13 columns],
      ft_version        model_mtr_name  model_mtr_ep         dataset_name  \
 0             0  ChemBerta_Medium_10m           0.0  bace_classification
 1             0  ChemBerta_Medium_10m           0.0  bace_classification
 2             0  ChemBerta_Medium_10m           0.0  bace_classification
 3             0  ChemBerta_Medium_10m           0.0  bace_classification
 4             0  ChemBerta_Medium_10m           0.0  bace_classification
 ..          ...                   ...           ...                  ...
 289           0  ChemBerta_Medium_10m           6.0         tox21_sr_p53
 290           0  ChemBerta_Medium_10m           6.0         tox21_sr_p53
 291           0  ChemBerta_Medium_10m           6.0         tox21_sr_p53
 292           0  ChemBerta_Medium_10m           6.0         tox21_sr_p53
 293           0  ChemBerta_Medium_10m           6.0         tox21_sr_p53

        dataset_type  metric_1  metric_2  p_value_mantissa  p_value_exponent  \
 0    classification  0.796739       NaN          4.229962             -11.0
 1    classification  0.795471       NaN          5.269794             -11.0
 2    classification  0.791486       NaN          1.041166             -10.0
 3    classification  0.805254       NaN          9.287435             -12.0
 4    classification  0.812138       NaN          2.585045             -12.0
 ..              ...       ...       ...               ...               ...
 289  classification  0.776259       NaN          2.937974             -10.0
 290  classification  0.809217       NaN          1.472491             -12.0
 291  classification  0.808074       NaN          1.788510             -12.0
 292  classification  0.804225       NaN          3.422991             -12.0
 293  classification  0.804045       NaN          3.527976             -12.0

      epoch      loss  loss_ranking  metric_1_ranking
 0        0  0.677749             2                 4
 1        1  0.730899             6                 5
 2        2  0.652241             0                 6
 3        3  0.672696             1                 3
 4        4  0.729119             5                 1
 ..     ...       ...           ...               ...
 289      2  0.172503             2                 4
 290      3  0.168121             1                 0
 291      4  0.158156             0                 1
 292      5  0.173501             3                 2
 293      6  0.176393             5                 3

 [294 rows x 13 columns],
      ft_version        model_mtr_name  model_mtr_ep         dataset_name  \
 0             0  ChemBerta_Medium_20m           0.0  bace_classification
 1             0  ChemBerta_Medium_20m           0.0  bace_classification
 2             0  ChemBerta_Medium_20m           0.0  bace_classification
 3             0  ChemBerta_Medium_20m           0.0  bace_classification
 4             0  ChemBerta_Medium_20m           0.0  bace_classification
 ..          ...                   ...           ...                  ...
 289           0  ChemBerta_Medium_20m           6.0         tox21_sr_p53
 290           0  ChemBerta_Medium_20m           6.0         tox21_sr_p53
 291           0  ChemBerta_Medium_20m           6.0         tox21_sr_p53
 292           0  ChemBerta_Medium_20m           6.0         tox21_sr_p53
 293           0  ChemBerta_Medium_20m           6.0         tox21_sr_p53

        dataset_type  metric_1  metric_2  p_value_mantissa  p_value_exponent  \
 0    classification  0.794022       NaN          6.762046             -11.0
 1    classification  0.790036       NaN          1.328824             -10.0
 2    classification  0.811594       NaN          2.864780             -12.0
 3    classification  0.805254       NaN          9.287435             -12.0
 4    classification  0.810145       NaN          3.762109             -12.0
 ..              ...       ...       ...               ...               ...
 289  classification  0.794181       NaN          1.786106             -11.0
 290  classification  0.782273       NaN          1.172286             -10.0
 291  classification  0.804285       NaN          3.388680             -12.0
 292  classification  0.811111       NaN          1.064896             -12.0
 293  classification  0.811983       NaN          9.166489             -13.0

      epoch      loss  loss_ranking  metric_1_ranking
 0        0  0.662994             1                 5
 1        1  0.725258             2                 6
 2        2  0.653109             0                 0
 3        3  0.738939             4                 4
 4        4  0.735574             3                 2
 ..     ...       ...           ...               ...
 289      2  0.168572             1                 3
 290      3  0.174650             4                 4
 291      4  0.158612             0                 2
 292      5  0.174601             3                 1
 293      6  0.176329             5                 0

 [294 rows x 13 columns],
      ft_version        model_mtr_name  model_mtr_ep         dataset_name  \

In [6]:
df_all_prev = pd.concat(list_df, axis=0, ignore_index=True).astype(dict_dtype.dict_dtype)
df_all_prev['p_value_exponent'] = df_all_prev['p_value_exponent'].fillna(0)
df_all_prev

,ft_version,model_mtr_name,model_mtr_ep,dataset_name,dataset_type,metric_1,metric_2,p_value_mantissa,p_value_exponent,epoch,loss,loss_ranking,metric_1_ranking
0,0,ChemBart_Medium_10m,0,bace_classification,classification,0.648188,NaN,0.001820,0.0,0,0.993232,6,6
1,0,ChemBart_Medium_10m,0,bace_classification,classification,0.760688,NaN,1.253343,-8.0,1,0.717989,5,5
2,0,ChemBart_Medium_10m,0,bace_classification,classification,0.805435,NaN,8.985626,-12.0,2,0.650228,0,3
3,0,ChemBart_Medium_10m,0,bace_classification,classification,0.800000,NaN,2.386729,-11.0,3,0.651059,1,4
4,0,ChemBart_Medium_10m,0,bace_classification,classification,0.808333,NaN,5.272629,-12.0,4,0.660707,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26455,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.773162,NaN,4.677256,-10.0,2,0.181836,5,3
26456,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.770786,NaN,6.656599,-10.0,3,0.169517,4,4
26457,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.808014,NaN,1.806867,-12.0,4,0.155549,0,2
26458,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.820493,NaN,2.071732,-13.0,5,0.160060,1,1
26459,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.820674,NaN,2.006469,-13.0,6,0.162564,2,0

In [7]:
# new_cols = df_all_prev['model_mtr_name'].str.split("_", expand=True).astype('category')
new_cols = df_all_prev['model_mtr_name'].str.split("_", expand=True)
list_new_cols = ['model_type', 'model_size', 'data_size']
new_cols.columns = list_new_cols
df_all = pd.concat([df_all_prev, new_cols], axis=1)
df_all

,ft_version,model_mtr_name,model_mtr_ep,dataset_name,dataset_type,metric_1,metric_2,p_value_mantissa,p_value_exponent,epoch,loss,loss_ranking,metric_1_ranking,model_type,model_size,data_size
0,0,ChemBart_Medium_10m,0,bace_classification,classification,0.648188,NaN,0.001820,0.0,0,0.993232,6,6,ChemBart,Medium,10m
1,0,ChemBart_Medium_10m,0,bace_classification,classification,0.760688,NaN,1.253343,-8.0,1,0.717989,5,5,ChemBart,Medium,10m
2,0,ChemBart_Medium_10m,0,bace_classification,classification,0.805435,NaN,8.985626,-12.0,2,0.650228,0,3,ChemBart,Medium,10m
3,0,ChemBart_Medium_10m,0,bace_classification,classification,0.800000,NaN,2.386729,-11.0,3,0.651059,1,4,ChemBart,Medium,10m
4,0,ChemBart_Medium_10m,0,bace_classification,classification,0.808333,NaN,5.272629,-12.0,4,0.660707,2,1,ChemBart,Medium,10m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26455,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.773162,NaN,4.677256,-10.0,2,0.181836,5,3,ChemLlama,Small,30m
26456,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.770786,NaN,6.656599,-10.0,3,0.169517,4,4,ChemLlama,Small,30m
26457,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.808014,NaN,1.806867,-12.0,4,0.155549,0,2,ChemLlama,Small,30m
26458,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.820493,NaN,2.071732,-13.0,5,0.160060,1,1,ChemLlama,Small,30m
26459,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.820674,NaN,2.006469,-13.0,6,0.162564,2,0,ChemLlama,Small,30m

In [8]:
# model type and size
df_all["mts"] = df_all['model_type'] + "_" + df_all["model_size"]
# model type and data size
df_all['mtds'] = df_all['model_type'] + "_" + df_all["data_size"]
# model size and data size
df_all['msds'] = df_all['model_size'] + "_" + df_all["data_size"]
df_all

,ft_version,model_mtr_name,model_mtr_ep,dataset_name,dataset_type,metric_1,metric_2,p_value_mantissa,p_value_exponent,epoch,loss,loss_ranking,metric_1_ranking,model_type,model_size,data_size,mts,mtds,msds
0,0,ChemBart_Medium_10m,0,bace_classification,classification,0.648188,NaN,0.001820,0.0,0,0.993232,6,6,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
1,0,ChemBart_Medium_10m,0,bace_classification,classification,0.760688,NaN,1.253343,-8.0,1,0.717989,5,5,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
2,0,ChemBart_Medium_10m,0,bace_classification,classification,0.805435,NaN,8.985626,-12.0,2,0.650228,0,3,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
3,0,ChemBart_Medium_10m,0,bace_classification,classification,0.800000,NaN,2.386729,-11.0,3,0.651059,1,4,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
4,0,ChemBart_Medium_10m,0,bace_classification,classification,0.808333,NaN,5.272629,-12.0,4,0.660707,2,1,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26455,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.773162,NaN,4.677256,-10.0,2,0.181836,5,3,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
26456,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.770786,NaN,6.656599,-10.0,3,0.169517,4,4,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
26457,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.808014,NaN,1.806867,-12.0,4,0.155549,0,2,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
26458,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.820493,NaN,2.071732,-13.0,5,0.160060,1,1,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
26459,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.820674,NaN,2.006469,-13.0,6,0.162564,2,0,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m

# Regression DF

In [9]:
df_reg = df_all[df_all['dataset_type'] == 'regression']
df_reg

,ft_version,model_mtr_name,model_mtr_ep,dataset_name,dataset_type,metric_1,metric_2,p_value_mantissa,p_value_exponent,epoch,loss,loss_ranking,metric_1_ranking,model_type,model_size,data_size,mts,mtds,msds
7,0,ChemBart_Medium_10m,0,bace_regression,regression,0.878964,0.731820,2.095776,-28.0,0,0.375684,0,0,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
8,0,ChemBart_Medium_10m,0,bace_regression,regression,1.015678,0.823957,4.048009,-25.0,1,0.552969,6,6,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
9,0,ChemBart_Medium_10m,0,bace_regression,regression,0.970207,0.802336,2.573282,-24.0,2,0.518979,4,4,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
10,0,ChemBart_Medium_10m,0,bace_regression,regression,0.996983,0.756401,2.810645,-21.0,3,0.488689,3,5,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
11,0,ChemBart_Medium_10m,0,bace_regression,regression,0.889537,0.681805,4.754197,-27.0,4,0.534026,5,1,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26448,4,ChemLlama_Small_30m,6,lipo,regression,0.791097,0.623674,1.391235,-29.0,2,0.612362,4,5,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
26449,4,ChemLlama_Small_30m,6,lipo,regression,0.780469,0.614752,2.166945,-35.0,3,0.596495,3,3,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
26450,4,ChemLlama_Small_30m,6,lipo,regression,0.752072,0.583458,3.094517,-39.0,4,0.572883,2,2,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
26451,4,ChemLlama_Small_30m,6,lipo,regression,0.738526,0.571243,5.030823,-41.0,5,0.561690,1,0,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
26452,4,ChemLlama_Small_30m,6,lipo,regression,0.741638,0.574454,1.132972,-40.0,6,0.557706,0,1,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m

### Best Regression

In [10]:
df_reg_best = df_reg.groupby(by=['ft_version', 'model_mtr_name', 'dataset_name'])['loss'].min().reset_index()
df_reg_best = pd.merge(df_reg, df_reg_best, on=['ft_version', 'model_mtr_name', 'dataset_name', 'loss'])
df_reg_best

,ft_version,model_mtr_name,model_mtr_ep,dataset_name,dataset_type,metric_1,metric_2,p_value_mantissa,p_value_exponent,epoch,loss,loss_ranking,metric_1_ranking,model_type,model_size,data_size,mts,mtds,msds
0,0,ChemBart_Medium_10m,4,delaney,regression,0.456320,0.357732,7.292727,-37.0,3,0.371624,0,3,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
1,0,ChemBart_Medium_10m,4,lipo,regression,0.721048,0.566975,2.102943,-43.0,6,0.534508,0,1,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
2,0,ChemBart_Medium_10m,6,bace_regression,regression,0.858430,0.718267,1.841017,-23.0,0,0.373197,0,0,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
3,0,ChemBart_Medium_20m,0,delaney,regression,0.473180,0.379224,7.223428,-40.0,6,0.383850,0,0,ChemBart,Medium,20m,ChemBart_Medium,ChemBart_20m,Medium_20m
4,0,ChemBart_Medium_20m,2,bace_regression,regression,0.815301,0.664588,3.910137,-24.0,3,0.374928,0,0,ChemBart,Medium,20m,ChemBart_Medium,ChemBart_20m,Medium_20m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,4,ChemLlama_Small_20m,1,bace_regression,regression,0.913419,0.755842,3.620652,-25.0,0,0.388239,0,1,ChemLlama,Small,20m,ChemLlama_Small,ChemLlama_20m,Small_20m
266,4,ChemLlama_Small_20m,6,delaney,regression,0.468015,0.381498,1.597436,-39.0,6,0.392031,0,1,ChemLlama,Small,20m,ChemLlama_Small,ChemLlama_20m,Small_20m
267,4,ChemLlama_Small_30m,1,bace_regression,regression,0.887489,0.721201,1.583451,-25.0,0,0.390893,0,3,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
268,4,ChemLlama_Small_30m,3,lipo,regression,0.746799,0.582347,1.576705,-40.0,5,0.544946,0,0,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
269,4,ChemLlama_Small_30m,6,delaney,regression,0.476766,0.395950,4.205481,-34.0,2,0.376626,0,0,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m

In [11]:
# df_reg_best.sort_values(by=['ft_version', 'model_mtr_name']).to_csv('./df_reg_best.csv', index=False)

In [12]:
df_reg_best.sort_values(by=['dataset_name', 'metric_1'], ascending=True)

,ft_version,model_mtr_name,model_mtr_ep,dataset_name,dataset_type,metric_1,metric_2,p_value_mantissa,p_value_exponent,epoch,loss,loss_ranking,metric_1_ranking,model_type,model_size,data_size,mts,mtds,msds
246,4,ChemBerta_Small_20m,0,bace_regression,regression,0.714798,0.577076,2.897342,-29.0,4,0.363430,0,0,ChemBerta,Small,20m,ChemBerta_Small,ChemBerta_20m,Small_20m
64,1,ChemBart_Small_10m,1,bace_regression,regression,0.754425,0.623590,8.168752,-28.0,3,0.410206,0,0,ChemBart,Small,10m,ChemBart_Small,ChemBart_10m,Small_10m
147,2,ChemLlama_Medium_20m,1,bace_regression,regression,0.764033,0.637440,4.116205,-26.0,1,0.384491,0,0,ChemLlama,Medium,20m,ChemLlama_Medium,ChemLlama_20m,Medium_20m
114,2,ChemBart_Medium_30m,1,bace_regression,regression,0.765883,0.611007,1.272846,-28.0,3,0.389012,0,0,ChemBart,Medium,30m,ChemBart_Medium,ChemBart_30m,Medium_30m
126,2,ChemBerta_Medium_10m,0,bace_regression,regression,0.784334,0.626046,6.174128,-28.0,1,0.371112,0,0,ChemBerta,Medium,10m,ChemBerta_Medium,ChemBerta_10m,Medium_10m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,2,ChemLlama_Small_10m,4,lipo,regression,0.764387,0.597764,2.794790,-38.0,6,0.518847,0,1,ChemLlama,Small,10m,ChemLlama_Small,ChemLlama_10m,Small_10m
158,2,ChemLlama_Small_20m,2,lipo,regression,0.766594,0.610190,5.638198,-34.0,5,0.537129,0,0,ChemLlama,Small,20m,ChemLlama_Small,ChemLlama_20m,Small_20m
101,1,ChemLlama_Small_10m,4,lipo,regression,0.769646,0.598591,7.212917,-40.0,6,0.546262,0,2,ChemLlama,Small,10m,ChemLlama_Small,ChemLlama_10m,Small_10m
57,1,ChemBart_Medium_20m,2,lipo,regression,0.770784,0.611809,2.087991,-36.0,6,0.530276,0,1,ChemBart,Medium,20m,ChemBart_Medium,ChemBart_20m,Medium_20m
136,2,ChemBerta_Small_10m,2,lipo,regression,0.809728,0.625368,1.070735,-36.0,5,0.527937,0,4,ChemBerta,Small,10m,ChemBerta_Small,ChemBerta_10m,Small_10m

# Best Reg only by Model Type

In [13]:
utils.calculate_SEM(df_reg_best.groupby(by=['model_type', 'dataset_name'])['metric_1'])

  model_type     dataset_name  metric_1  standard_error
0   ChemBart  bace_regression  0.895847        0.029971
1   ChemBart          delaney  0.478322        0.012365
2   ChemBart             lipo  0.737041        0.004775
3  ChemBerta  bace_regression  0.922637        0.037720
4  ChemBerta          delaney  0.488503        0.018287
5  ChemBerta             lipo  0.735585        0.006088
6  ChemLlama  bace_regression  0.918288        0.029837
7  ChemLlama          delaney  0.491942        0.031576
8  ChemLlama             lipo  0.741595        0.005231

In [14]:
utils.calculate_SEM(df_reg_best.groupby(by=['model_mtr_name', 'dataset_name'])['metric_1'])

          model_mtr_name     dataset_name  metric_1  standard_error
0    ChemBart_Medium_10m  bace_regression  0.875031        0.008909
1    ChemBart_Medium_10m          delaney  0.471799        0.004381
2    ChemBart_Medium_10m             lipo  0.730690        0.002637
3    ChemBart_Medium_20m  bace_regression  0.854170        0.007054
4    ChemBart_Medium_20m          delaney  0.508952        0.008036
5    ChemBart_Medium_20m             lipo  0.736278        0.002765
6    ChemBart_Medium_30m  bace_regression  0.874283        0.013085
7    ChemBart_Medium_30m          delaney  0.474759        0.004323
8    ChemBart_Medium_30m             lipo  0.730323        0.002143
9     ChemBart_Small_10m  bace_regression  0.879805        0.014006
10    ChemBart_Small_10m          delaney  0.446414        0.003053
11    ChemBart_Small_10m             lipo  0.740763        0.001255
12    ChemBart_Small_20m  bace_regression  0.999640        0.014087
13    ChemBart_Small_20m          delaney  0.482503        0.002909
14    ChemBart_Small_20m             lipo  0.739479        0.001608
15    ChemBart_Small_30m  bace_regression  0.892152        0.008589
16    ChemBart_Small_30m          delaney  0.485507        0.004041
17    ChemBart_Small_30m             lipo  0.744712        0.000614
18  ChemBerta_Medium_10m  bace_regression  0.869254        0.009031
19  ChemBerta_Medium_10m          delaney  0.492071        0.009698
20  ChemBerta_Medium_10m             lipo  0.735575        0.002065
21  ChemBerta_Medium_20m  bace_regression  1.011261        0.027038
22  ChemBerta_Medium_20m          delaney  0.502195        0.010006
23  ChemBerta_Medium_20m             lipo  0.731561        0.001342
24  ChemBerta_Medium_30m  bace_regression  0.907469        0.006380
25  ChemBerta_Medium_30m          delaney  0.491555        0.003516
26  ChemBerta_Medium_30m             lipo  0.725919        0.001819
27   ChemBerta_Small_10m  bace_regression  0.936273        0.013724
28   ChemBerta_Small_10m          delaney  0.484950        0.008053
29   ChemBerta_Small_10m             lipo  0.742060        0.005300
30   ChemBerta_Small_20m  bace_regression  0.849056        0.010427
31   ChemBerta_Small_20m          delaney  0.459286        0.003314
32   ChemBerta_Small_20m             lipo  0.735858        0.001159
33   ChemBerta_Small_30m  bace_regression  0.962511        0.012216
34   ChemBerta_Small_30m          delaney  0.500960        0.009657
35   ChemBerta_Small_30m             lipo  0.742540        0.001161
36  ChemLlama_Medium_10m  bace_regression  0.894889        0.007618
37  ChemLlama_Medium_10m          delaney  0.453826        0.003289
38  ChemLlama_Medium_10m             lipo  0.726755        0.001246
39  ChemLlama_Medium_20m  bace_regression  0.855521        0.008046
40  ChemLlama_Medium_20m          delaney  0.458282        0.001444
41  ChemLlama_Medium_20m             lipo  0.743794        0.001823
42  ChemLlama_Medium_30m  bace_regression  0.931373        0.009344
43  ChemLlama_Medium_30m          delaney  0.444439        0.001626
44  ChemLlama_Medium_30m             lipo  0.734313        0.000789
45   ChemLlama_Small_10m  bace_regression  0.950595        0.022421
46   ChemLlama_Small_10m          delaney  0.523875        0.006504
47   ChemLlama_Small_10m             lipo  0.752772        0.002269
48   ChemLlama_Small_20m  bace_regression  0.942964        0.012700
49   ChemLlama_Small_20m          delaney  0.550273        0.024857
50   ChemLlama_Small_20m             lipo  0.748708        0.002355
51   ChemLlama_Small_30m  bace_regression  0.934384        0.007040
52   ChemLlama_Small_30m          delaney  0.520953        0.017178
53   ChemLlama_Small_30m             lipo  0.743230        0.002513

In [15]:
utils.calculate_SEM(df_reg_best.groupby(by=['mts', 'dataset_name'])['metric_1'])

                 mts     dataset_name  metric_1  standard_error
0    ChemBart_Medium  bace_regression  0.867828        0.016217
1    ChemBart_Medium          delaney  0.485170        0.010234
2    ChemBart_Medium             lipo  0.732430        0.004110
3     ChemBart_Small  bace_regression  0.923866        0.023956
4     ChemBart_Small          delaney  0.471475        0.006930
5     ChemBart_Small             lipo  0.741651        0.002046
6   ChemBerta_Medium  bace_regression  0.929328        0.030752
7   ChemBerta_Medium          delaney  0.495274        0.013359
8   ChemBerta_Medium             lipo  0.731018        0.002995
9    ChemBerta_Small  bace_regression  0.915947        0.022859
10   ChemBerta_Small          delaney  0.481732        0.012746
11   ChemBerta_Small             lipo  0.740153        0.005190
12  ChemLlama_Medium  bace_regression  0.893928        0.015400
13  ChemLlama_Medium          delaney  0.452183        0.003912
14  ChemLlama_Medium             lipo  0.734954        0.002758
15   ChemLlama_Small  bace_regression  0.942648        0.024783
16   ChemLlama_Small          delaney  0.531700        0.028795
17   ChemLlama_Small             lipo  0.748236        0.003935

In [16]:
utils.calculate_SEM(df_reg_best.groupby(by=['mtds', 'dataset_name'])['metric_1'])

             mtds     dataset_name  metric_1  standard_error
0    ChemBart_10m  bace_regression  0.877418        0.015657
1    ChemBart_10m          delaney  0.459106        0.005655
2    ChemBart_10m             lipo  0.735726        0.002937
3    ChemBart_20m  bace_regression  0.926905        0.020937
4    ChemBart_20m          delaney  0.495727        0.008492
5    ChemBart_20m             lipo  0.737878        0.003034
6    ChemBart_30m  bace_regression  0.883218        0.014868
7    ChemBart_30m          delaney  0.480133        0.005685
8    ChemBart_30m             lipo  0.737518        0.002559
9   ChemBerta_10m  bace_regression  0.902763        0.016915
10  ChemBerta_10m          delaney  0.488510        0.011906
11  ChemBerta_10m             lipo  0.738817        0.005403
12  ChemBerta_20m  bace_regression  0.930158        0.031893
13  ChemBerta_20m          delaney  0.480740        0.010849
14  ChemBerta_20m             lipo  0.733709        0.001728
15  ChemBerta_30m  bace_regression  0.934990        0.014142
16  ChemBerta_30m          delaney  0.496257        0.009736
17  ChemBerta_30m             lipo  0.734230        0.002642
18  ChemLlama_10m  bace_regression  0.922742        0.023030
19  ChemLlama_10m          delaney  0.488851        0.009884
20  ChemLlama_10m             lipo  0.739763        0.003595
21  ChemLlama_20m  bace_regression  0.899242        0.016720
22  ChemLlama_20m          delaney  0.504278        0.025261
23  ChemLlama_20m             lipo  0.746251        0.002852
24  ChemLlama_30m  bace_regression  0.932878        0.011034
25  ChemLlama_30m          delaney  0.482696        0.018024
26  ChemLlama_30m             lipo  0.738771        0.002643

In [17]:
utils.calculate_SEM(df_reg_best.groupby(by=['msds', 'dataset_name'])['metric_1'])

          msds     dataset_name  metric_1  standard_error
0   Medium_10m  bace_regression  0.879725        0.013959
1   Medium_10m          delaney  0.472565        0.010994
2   Medium_10m             lipo  0.731007        0.003424
3   Medium_20m  bace_regression  0.906984        0.032379
4   Medium_20m          delaney  0.489810        0.013153
5   Medium_20m             lipo  0.737211        0.003530
6   Medium_30m  bace_regression  0.904375        0.017003
7   Medium_30m          delaney  0.470251        0.007177
8   Medium_30m             lipo  0.730185        0.002829
9    Small_10m  bace_regression  0.922224        0.028567
10   Small_10m          delaney  0.485080        0.012624
11   Small_10m             lipo  0.745198        0.005618
12   Small_20m  bace_regression  0.930553        0.025121
13   Small_20m          delaney  0.497354        0.025198
14   Small_20m             lipo  0.741348        0.003140
15   Small_30m  bace_regression  0.929682        0.016835
16   Small_30m          delaney  0.502473        0.018958
17   Small_30m             lipo  0.743494        0.002634

In [18]:
df_reg_best

,ft_version,model_mtr_name,model_mtr_ep,dataset_name,dataset_type,metric_1,metric_2,p_value_mantissa,p_value_exponent,epoch,loss,loss_ranking,metric_1_ranking,model_type,model_size,data_size,mts,mtds,msds
0,0,ChemBart_Medium_10m,4,delaney,regression,0.456320,0.357732,7.292727,-37.0,3,0.371624,0,3,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
1,0,ChemBart_Medium_10m,4,lipo,regression,0.721048,0.566975,2.102943,-43.0,6,0.534508,0,1,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
2,0,ChemBart_Medium_10m,6,bace_regression,regression,0.858430,0.718267,1.841017,-23.0,0,0.373197,0,0,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
3,0,ChemBart_Medium_20m,0,delaney,regression,0.473180,0.379224,7.223428,-40.0,6,0.383850,0,0,ChemBart,Medium,20m,ChemBart_Medium,ChemBart_20m,Medium_20m
4,0,ChemBart_Medium_20m,2,bace_regression,regression,0.815301,0.664588,3.910137,-24.0,3,0.374928,0,0,ChemBart,Medium,20m,ChemBart_Medium,ChemBart_20m,Medium_20m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,4,ChemLlama_Small_20m,1,bace_regression,regression,0.913419,0.755842,3.620652,-25.0,0,0.388239,0,1,ChemLlama,Small,20m,ChemLlama_Small,ChemLlama_20m,Small_20m
266,4,ChemLlama_Small_20m,6,delaney,regression,0.468015,0.381498,1.597436,-39.0,6,0.392031,0,1,ChemLlama,Small,20m,ChemLlama_Small,ChemLlama_20m,Small_20m
267,4,ChemLlama_Small_30m,1,bace_regression,regression,0.887489,0.721201,1.583451,-25.0,0,0.390893,0,3,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
268,4,ChemLlama_Small_30m,3,lipo,regression,0.746799,0.582347,1.576705,-40.0,5,0.544946,0,0,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
269,4,ChemLlama_Small_30m,6,delaney,regression,0.476766,0.395950,4.205481,-34.0,2,0.376626,0,0,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m

## Best Reg Avg By Epoch

In [19]:
# df_reg_best_ep
df_reg_best_ep = df_reg.groupby(by=['ft_version', 'model_mtr_name', 'model_mtr_ep','dataset_name'])['metric_1'].min().reset_index()
df_reg_best_ep = pd.merge(df_reg, df_reg_best_ep, on=['ft_version', 'model_mtr_name', 'model_mtr_ep', 'dataset_name', 'metric_1'])
df_reg_best_ep

,ft_version,model_mtr_name,model_mtr_ep,dataset_name,dataset_type,metric_1,metric_2,p_value_mantissa,p_value_exponent,epoch,loss,loss_ranking,metric_1_ranking,model_type,model_size,data_size,mts,mtds,msds
0,0,ChemBart_Medium_10m,0,bace_regression,regression,0.878964,0.731820,2.095776,-28.0,0,0.375684,0,0,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
1,0,ChemBart_Medium_10m,0,delaney,regression,0.473740,0.385443,1.035222,-37.0,6,0.404661,0,0,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
2,0,ChemBart_Medium_10m,0,lipo,regression,0.748903,0.579198,3.535616,-41.0,5,0.582682,0,0,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
3,0,ChemBart_Medium_10m,1,bace_regression,regression,0.851791,0.687378,1.711962,-24.0,3,0.443988,1,0,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
4,0,ChemBart_Medium_10m,1,delaney,regression,0.429409,0.357494,1.063178,-39.0,5,0.443409,2,0,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1885,4,ChemLlama_Small_30m,5,delaney,regression,0.435942,0.356790,1.598363,-38.0,4,0.417539,2,0,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
1886,4,ChemLlama_Small_30m,5,lipo,regression,0.724260,0.564762,1.706134,-43.0,5,0.556957,1,0,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
1887,4,ChemLlama_Small_30m,6,bace_regression,regression,0.829506,0.667297,3.489122,-26.0,0,0.420002,0,0,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
1888,4,ChemLlama_Small_30m,6,delaney,regression,0.476766,0.395950,4.205481,-34.0,2,0.376626,0,0,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
1889,4,ChemLlama_Small_30m,6,lipo,regression,0.738526,0.571243,5.030823,-41.0,5,0.561690,1,0,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m

In [20]:
df_reg_best_ep_mean = df_reg_best_ep.groupby(by=['model_mtr_name', 'dataset_name', 'model_mtr_ep'])['metric_1'].mean()
df_reg_best_ep_mean = pd.merge(
    df_reg_best_ep_mean,
    df_reg_best_ep[["model_mtr_name", "model_mtr_ep", "dataset_name", "metric_1", "model_type", "model_size", "data_size", "mts", "mtds", "msds"]],
    on=['model_mtr_name', 'dataset_name', 'model_mtr_ep']
)
df_reg_best_ep_mean = df_reg_best_ep_mean.rename(columns={
    'metric_1_x': 'metric_1_mean',
    'metric_1_y': 'metric_1'
})

df_reg_best_ep_mean = df_reg_best_ep_mean.drop_duplicates(subset=['model_mtr_name', 'dataset_name', 'model_mtr_ep'], keep='first')
df_reg_best_ep_mean.drop(columns=['metric_1'], inplace=True)
df_reg_best_ep_mean

,model_mtr_name,dataset_name,model_mtr_ep,metric_1_mean,model_type,model_size,data_size,mts,mtds,msds
0,ChemBart_Medium_10m,bace_regression,0,0.852204,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
5,ChemBart_Medium_10m,bace_regression,1,0.858871,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
10,ChemBart_Medium_10m,bace_regression,2,0.813708,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
15,ChemBart_Medium_10m,bace_regression,3,0.875578,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
20,ChemBart_Medium_10m,bace_regression,4,0.864862,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
...,...,...,...,...,...,...,...,...,...,...
1865,ChemLlama_Small_30m,lipo,2,0.737494,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
1870,ChemLlama_Small_30m,lipo,3,0.743630,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
1875,ChemLlama_Small_30m,lipo,4,0.733452,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
1880,ChemLlama_Small_30m,lipo,5,0.742287,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
1885,ChemLlama_Small_30m,lipo,6,0.737726,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m

# Classification DF

In [21]:
df_cls = df_all[df_all['dataset_type'] == 'classification']
df_cls

,ft_version,model_mtr_name,model_mtr_ep,dataset_name,dataset_type,metric_1,metric_2,p_value_mantissa,p_value_exponent,epoch,loss,loss_ranking,metric_1_ranking,model_type,model_size,data_size,mts,mtds,msds
0,0,ChemBart_Medium_10m,0,bace_classification,classification,0.648188,NaN,0.001820,0.0,0,0.993232,6,6,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
1,0,ChemBart_Medium_10m,0,bace_classification,classification,0.760688,NaN,1.253343,-8.0,1,0.717989,5,5,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
2,0,ChemBart_Medium_10m,0,bace_classification,classification,0.805435,NaN,8.985626,-12.0,2,0.650228,0,3,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
3,0,ChemBart_Medium_10m,0,bace_classification,classification,0.800000,NaN,2.386729,-11.0,3,0.651059,1,4,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
4,0,ChemBart_Medium_10m,0,bace_classification,classification,0.808333,NaN,5.272629,-12.0,4,0.660707,2,1,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26455,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.773162,NaN,4.677256,-10.0,2,0.181836,5,3,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
26456,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.770786,NaN,6.656599,-10.0,3,0.169517,4,4,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
26457,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.808014,NaN,1.806867,-12.0,4,0.155549,0,2,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
26458,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.820493,NaN,2.071732,-13.0,5,0.160060,1,1,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
26459,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.820674,NaN,2.006469,-13.0,6,0.162564,2,0,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m

### Best Classification

In [22]:
df_cls_best = df_cls.groupby(by=['ft_version', 'model_mtr_name', 'dataset_name'])['loss'].min().reset_index()
df_cls_best = pd.merge(df_cls, df_cls_best, on=['ft_version', 'model_mtr_name', 'dataset_name', 'loss'])
df_cls_best

,ft_version,model_mtr_name,model_mtr_ep,dataset_name,dataset_type,metric_1,metric_2,p_value_mantissa,p_value_exponent,epoch,loss,loss_ranking,metric_1_ranking,model_type,model_size,data_size,mts,mtds,msds
0,0,ChemBart_Medium_10m,0,bace_classification,classification,0.805435,NaN,8.985626,-12.0,2,0.650228,0,3,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
1,0,ChemBart_Medium_10m,2,tox21_sr_p53,classification,0.757736,NaN,4.367270,-9.0,4,0.160418,0,4,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
2,0,ChemBart_Medium_10m,5,hiv,classification,0.772591,NaN,1.482182,-26.0,6,0.077621,0,1,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
3,0,ChemBart_Medium_20m,1,bace_classification,classification,0.818297,NaN,7.892324,-13.0,3,0.666523,0,1,ChemBart,Medium,20m,ChemBart_Medium,ChemBart_20m,Medium_20m
4,0,ChemBart_Medium_20m,5,hiv,classification,0.777692,NaN,1.645820,-27.0,6,0.077180,0,1,ChemBart,Medium,20m,ChemBart_Medium,ChemBart_20m,Medium_20m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,4,ChemLlama_Small_20m,6,hiv,classification,0.798432,NaN,1.394515,-31.0,6,0.078940,0,0,ChemLlama,Small,20m,ChemLlama_Small,ChemLlama_20m,Small_20m
266,4,ChemLlama_Small_20m,6,tox21_sr_p53,classification,0.808766,NaN,1.590101,-12.0,4,0.156561,0,0,ChemLlama,Small,20m,ChemLlama_Small,ChemLlama_20m,Small_20m
267,4,ChemLlama_Small_30m,0,hiv,classification,0.789028,NaN,1.068286,-29.0,6,0.077833,0,0,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
268,4,ChemLlama_Small_30m,3,bace_classification,classification,0.804891,NaN,9.920823,-12.0,2,0.679348,0,1,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
269,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.808014,NaN,1.806867,-12.0,4,0.155549,0,2,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m

In [23]:
# df_cls_best.sort_values(by=['ft_version', 'model_mtr_name']).to_csv('./df_cls_best.csv', index=False)

# Best CLS only by Model Type

In [24]:
utils.calculate_SEM(df_cls_best.groupby(by=['model_type', 'dataset_name'])['metric_1'])

  model_type         dataset_name  metric_1  standard_error
0   ChemBart  bace_classification  0.794559        0.008263
1   ChemBart                  hiv  0.761090        0.004460
2   ChemBart         tox21_sr_p53  0.788581        0.007211
3  ChemBerta  bace_classification  0.802156        0.003802
4  ChemBerta                  hiv  0.758133        0.007284
5  ChemBerta         tox21_sr_p53  0.788588        0.006989
6  ChemLlama  bace_classification  0.792156        0.005415
7  ChemLlama                  hiv  0.769427        0.008741
8  ChemLlama         tox21_sr_p53  0.789914        0.007250

In [25]:
utils.calculate_SEM(df_cls_best.groupby(by=['model_mtr_name', 'dataset_name'])['metric_1'])

          model_mtr_name         dataset_name  metric_1  standard_error
0    ChemBart_Medium_10m  bace_classification  0.808514        0.001443
1    ChemBart_Medium_10m                  hiv  0.752857        0.001727
2    ChemBart_Medium_10m         tox21_sr_p53  0.776235        0.001987
3    ChemBart_Medium_20m  bace_classification  0.793877        0.002222
4    ChemBart_Medium_20m                  hiv  0.771590        0.001927
5    ChemBart_Medium_20m         tox21_sr_p53  0.786303        0.001284
6    ChemBart_Medium_30m  bace_classification  0.801957        0.000936
7    ChemBart_Medium_30m                  hiv  0.760252        0.001048
8    ChemBart_Medium_30m         tox21_sr_p53  0.784487        0.003456
9     ChemBart_Small_10m  bace_classification  0.798659        0.003296
10    ChemBart_Small_10m                  hiv  0.756202        0.002664
11    ChemBart_Small_10m         tox21_sr_p53  0.795402        0.002395
12    ChemBart_Small_20m  bace_classification  0.794312        0.004540
13    ChemBart_Small_20m                  hiv  0.758211        0.001114
14    ChemBart_Small_20m         tox21_sr_p53  0.788823        0.005346
15    ChemBart_Small_30m  bace_classification  0.770036        0.004801
16    ChemBart_Small_30m                  hiv  0.767424        0.001445
17    ChemBart_Small_30m         tox21_sr_p53  0.800238        0.001647
18  ChemBerta_Medium_10m  bace_classification  0.802572        0.000895
19  ChemBerta_Medium_10m                  hiv  0.758088        0.004108
20  ChemBerta_Medium_10m         tox21_sr_p53  0.792738        0.002249
21  ChemBerta_Medium_20m  bace_classification  0.802392        0.000946
22  ChemBerta_Medium_20m                  hiv  0.753449        0.002882
23  ChemBerta_Medium_20m         tox21_sr_p53  0.772573        0.004052
24  ChemBerta_Medium_30m  bace_classification  0.801196        0.001854
25  ChemBerta_Medium_30m                  hiv  0.767157        0.001681
26  ChemBerta_Medium_30m         tox21_sr_p53  0.797910        0.002555
27   ChemBerta_Small_10m  bace_classification  0.796196        0.001775
28   ChemBerta_Small_10m                  hiv  0.744489        0.004458
29   ChemBerta_Small_10m         tox21_sr_p53  0.781966        0.001760
30   ChemBerta_Small_20m  bace_classification  0.799167        0.001878
31   ChemBerta_Small_20m                  hiv  0.757424        0.001060
32   ChemBerta_Small_20m         tox21_sr_p53  0.793321        0.003572
33   ChemBerta_Small_30m  bace_classification  0.811413        0.001618
34   ChemBerta_Small_30m                  hiv  0.768192        0.002459
35   ChemBerta_Small_30m         tox21_sr_p53  0.793018        0.002198
36  ChemLlama_Medium_10m  bace_classification  0.784348        0.002921
37  ChemLlama_Medium_10m                  hiv  0.767263        0.001115
38  ChemLlama_Medium_10m         tox21_sr_p53  0.779398        0.003414
39  ChemLlama_Medium_20m  bace_classification  0.807355        0.002642
40  ChemLlama_Medium_20m                  hiv  0.753815        0.002811
41  ChemLlama_Medium_20m         tox21_sr_p53  0.799744        0.001462
42  ChemLlama_Medium_30m  bace_classification  0.794819        0.001022
43  ChemLlama_Medium_30m                  hiv  0.771438        0.004063
44  ChemLlama_Medium_30m         tox21_sr_p53  0.801525        0.001432
45   ChemLlama_Small_10m  bace_classification  0.791558        0.001217
46   ChemLlama_Small_10m                  hiv  0.756855        0.006349
47   ChemLlama_Small_10m         tox21_sr_p53  0.791920        0.001165
48   ChemLlama_Small_20m  bace_classification  0.783152        0.002571
49   ChemLlama_Small_20m                  hiv  0.781150        0.002666
50   ChemLlama_Small_20m         tox21_sr_p53  0.770444        0.005025
51   ChemLlama_Small_30m  bace_classification  0.791703        0.001405
52   ChemLlama_Small_30m                  hiv  0.786043        0.000424
53   ChemLlama_Small_30m         tox21_sr_p53  0.796455        0.001809

In [26]:
utils.calculate_SEM(df_cls_best.groupby(by=['mts', 'dataset_name'])['metric_1'])

                 mts         dataset_name  metric_1  standard_error
0    ChemBart_Medium  bace_classification  0.801449        0.002984
1    ChemBart_Medium                  hiv  0.761566        0.003196
2    ChemBart_Medium         tox21_sr_p53  0.782342        0.004022
3     ChemBart_Small  bace_classification  0.787669        0.007495
4     ChemBart_Small                  hiv  0.760613        0.003218
5     ChemBart_Small         tox21_sr_p53  0.794821        0.005748
6   ChemBerta_Medium  bace_classification  0.802053        0.002103
7   ChemBerta_Medium                  hiv  0.759565        0.005093
8   ChemBerta_Medium         tox21_sr_p53  0.787740        0.005578
9    ChemBerta_Small  bace_classification  0.802258        0.003248
10   ChemBerta_Small                  hiv  0.756702        0.005364
11   ChemBerta_Small         tox21_sr_p53  0.789435        0.004404
12  ChemLlama_Medium  bace_classification  0.795507        0.004411
13  ChemLlama_Medium                  hiv  0.764172        0.005036
14  ChemLlama_Medium         tox21_sr_p53  0.793556        0.004425
15   ChemLlama_Small  bace_classification  0.788804        0.003095
16   ChemLlama_Small                  hiv  0.774683        0.007106
17   ChemLlama_Small         tox21_sr_p53  0.786273        0.005769

In [27]:
utils.calculate_SEM(df_cls_best.groupby(by=['mtds', 'dataset_name'])['metric_1'])

             mtds         dataset_name  metric_1  standard_error
0    ChemBart_10m  bace_classification  0.803587        0.003536
1    ChemBart_10m                  hiv  0.754529        0.003013
2    ChemBart_10m         tox21_sr_p53  0.785819        0.003520
3    ChemBart_20m  bace_classification  0.794094        0.004766
4    ChemBart_20m                  hiv  0.764901        0.002499
5    ChemBart_20m         tox21_sr_p53  0.787563        0.005190
6    ChemBart_30m  bace_classification  0.785996        0.005634
7    ChemBart_30m                  hiv  0.763838        0.001833
8    ChemBart_30m         tox21_sr_p53  0.792362        0.003947
9   ChemBerta_10m  bace_classification  0.799384        0.001983
10  ChemBerta_10m                  hiv  0.751288        0.005880
11  ChemBerta_10m         tox21_sr_p53  0.787352        0.002906
12  ChemBerta_20m  bace_classification  0.800779        0.002009
13  ChemBerta_20m                  hiv  0.755437        0.002923
14  ChemBerta_20m         tox21_sr_p53  0.782947        0.005510
15  ChemBerta_30m  bace_classification  0.806304        0.002541
16  ChemBerta_30m                  hiv  0.767674        0.002811
17  ChemBerta_30m         tox21_sr_p53  0.795464        0.003216
18  ChemLlama_10m  bace_classification  0.787953        0.003072
19  ChemLlama_10m                  hiv  0.762059        0.006169
20  ChemLlama_10m         tox21_sr_p53  0.785659        0.003630
21  ChemLlama_20m  bace_classification  0.795254        0.004255
22  ChemLlama_20m                  hiv  0.767483        0.004586
23  ChemLlama_20m         tox21_sr_p53  0.785094        0.005760
24  ChemLlama_30m  bace_classification  0.793261        0.001668
25  ChemLlama_30m                  hiv  0.778740        0.004127
26  ChemLlama_30m         tox21_sr_p53  0.798990        0.002236

In [28]:
utils.calculate_SEM(df_cls_best.groupby(by=['msds', 'dataset_name'])['metric_1'])

          msds         dataset_name  metric_1  standard_error
0   Medium_10m  bace_classification  0.798478        0.004010
1   Medium_10m                  hiv  0.759402        0.004495
2   Medium_10m         tox21_sr_p53  0.782790        0.004555
3   Medium_20m  bace_classification  0.801208        0.003581
4   Medium_20m                  hiv  0.759618        0.004620
5   Medium_20m         tox21_sr_p53  0.786207        0.004964
6   Medium_30m  bace_classification  0.799324        0.002281
7   Medium_30m                  hiv  0.766282        0.004334
8   Medium_30m         tox21_sr_p53  0.794640        0.004559
9    Small_10m  bace_classification  0.795471        0.003714
10   Small_10m                  hiv  0.752515        0.007719
11   Small_10m         tox21_sr_p53  0.789763        0.003266
12   Small_20m  bace_classification  0.792210        0.005388
13   Small_20m                  hiv  0.765595        0.003915
14   Small_20m         tox21_sr_p53  0.784196        0.007931
15   Small_30m  bace_classification  0.791051        0.006379
16   Small_30m                  hiv  0.773886        0.003396
17   Small_30m         tox21_sr_p53  0.796570        0.003129

## Best Class Avg By Epoch

In [29]:
# df_cls_best_ep
df_cls_best_ep = df_cls.groupby(by=['ft_version', 'model_mtr_name', 'model_mtr_ep','dataset_name'])['metric_1'].max().reset_index()
df_cls_best_ep = pd.merge(df_cls, df_cls_best_ep, on=['ft_version', 'model_mtr_name', 'model_mtr_ep', 'dataset_name', 'metric_1'])
df_cls_best_ep

,ft_version,model_mtr_name,model_mtr_ep,dataset_name,dataset_type,metric_1,metric_2,p_value_mantissa,p_value_exponent,epoch,loss,loss_ranking,metric_1_ranking,model_type,model_size,data_size,mts,mtds,msds
0,0,ChemBart_Medium_10m,0,bace_classification,classification,0.811413,NaN,2.964394,-12.0,5,0.681843,4,0,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
1,0,ChemBart_Medium_10m,0,hiv,classification,0.779646,NaN,7.010327,-28.0,4,0.081900,2,0,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
2,0,ChemBart_Medium_10m,0,tox21_sr_p53,classification,0.810510,NaN,1.180567,-12.0,5,0.179241,3,0,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
3,0,ChemBart_Medium_10m,1,bace_classification,classification,0.811051,NaN,3.173805,-12.0,3,0.685923,0,0,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
4,0,ChemBart_Medium_10m,1,hiv,classification,0.777790,NaN,1.576771,-27.0,2,0.082176,0,0,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1900,4,ChemLlama_Small_30m,5,hiv,classification,0.782080,NaN,2.401455,-28.0,5,0.084080,0,0,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
1901,4,ChemLlama_Small_30m,5,tox21_sr_p53,classification,0.825786,NaN,8.034399,-14.0,6,0.162883,0,0,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
1902,4,ChemLlama_Small_30m,6,bace_classification,classification,0.816848,NaN,1.047220,-12.0,1,0.736842,1,0,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
1903,4,ChemLlama_Small_30m,6,hiv,classification,0.788864,NaN,1.150852,-29.0,5,0.087338,3,0,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
1904,4,ChemLlama_Small_30m,6,tox21_sr_p53,classification,0.820674,NaN,2.006469,-13.0,6,0.162564,2,0,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m

In [30]:
df_cls_best_ep_mean = df_cls_best_ep.groupby(by=['model_mtr_name', 'dataset_name', 'model_mtr_ep'])['metric_1'].mean()
df_cls_best_ep_mean = pd.merge(
    df_cls_best_ep_mean,
    df_cls_best_ep[["model_mtr_name", "model_mtr_ep", "dataset_name", "metric_1", "model_type", "model_size", "data_size", "mts", "mtds", "msds"]],
    on=['model_mtr_name', 'dataset_name', 'model_mtr_ep']
)
df_cls_best_ep_mean = df_cls_best_ep_mean.rename(columns={
    'metric_1_x': 'metric_1_mean',
    'metric_1_y': 'metric_1'
})

df_cls_best_ep_mean = df_cls_best_ep_mean.drop_duplicates(subset=['model_mtr_name', 'dataset_name', 'model_mtr_ep'], keep='first')
df_cls_best_ep_mean.drop(columns=['metric_1'], inplace=True)
df_cls_best_ep_mean

,model_mtr_name,dataset_name,model_mtr_ep,metric_1_mean,model_type,model_size,data_size,mts,mtds,msds
0,ChemBart_Medium_10m,bace_classification,0,0.816775,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
5,ChemBart_Medium_10m,bace_classification,1,0.804197,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
11,ChemBart_Medium_10m,bace_classification,2,0.810688,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
16,ChemBart_Medium_10m,bace_classification,3,0.811449,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
21,ChemBart_Medium_10m,bace_classification,4,0.814384,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
...,...,...,...,...,...,...,...,...,...,...
1880,ChemLlama_Small_30m,tox21_sr_p53,2,0.807208,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
1885,ChemLlama_Small_30m,tox21_sr_p53,3,0.800460,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
1890,ChemLlama_Small_30m,tox21_sr_p53,4,0.805416,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
1895,ChemLlama_Small_30m,tox21_sr_p53,5,0.806306,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m
1900,ChemLlama_Small_30m,tox21_sr_p53,6,0.795926,ChemLlama,Small,30m,ChemLlama_Small,ChemLlama_30m,Small_30m

# TES and STD

In [31]:
def TES_STD_calculator_low_level(well_ordered_df, is_reg, by:str):
    list_ds_name = sorted(well_ordered_df['dataset_name'].unique())

    ser_groupby = well_ordered_df.groupby(by=[by]+['dataset_name'])['metric_1']
    avg_of_best = ser_groupby.mean()
    df_avg_of_best = avg_of_best.reset_index()

    list_best_metric = list()
    for ds in list_ds_name:
        if is_reg:
            local_best = df_avg_of_best[df_avg_of_best['dataset_name'] == ds]['metric_1'].min()
        else:
            local_best = df_avg_of_best[df_avg_of_best['dataset_name'] == ds]['metric_1'].max()
        list_best_metric.append(local_best)
    # now it is an array
    list_best_metric = np.array(list_best_metric)

    list_error = list()
    list_mt = sorted(well_ordered_df[by].unique())
    for mt in list_mt:
        list_error_ds = list()
        for idx, ds in enumerate(list_ds_name):
            local_df = well_ordered_df[well_ordered_df[by] == mt]
            arr_local_metric = local_df[local_df['dataset_name'] == ds]['metric_1']
            # local_ae = np.abs(arr_local_metric - list_best_metric[idx])
            if is_reg:
                local_ae = arr_local_metric - list_best_metric[idx]
            else:
                local_ae = list_best_metric[idx] - arr_local_metric
            llist_error_ds.append(local_ae)
        list_error.append(list_error_ds)

    return np.array(list_error)

# Std from Low Level

## overall TES and STD

## Model Type

In [32]:
utils.calculate_SEM(df_reg_best.groupby(by=['model_type', 'dataset_name'])['metric_1']).sort_values(by=['dataset_name', 'metric_1'])

  model_type     dataset_name  metric_1  standard_error
0   ChemBart  bace_regression  0.895847        0.029971
6  ChemLlama  bace_regression  0.918288        0.029837
3  ChemBerta  bace_regression  0.922637        0.037720
1   ChemBart          delaney  0.478322        0.012365
4  ChemBerta          delaney  0.488503        0.018287
7  ChemLlama          delaney  0.491942        0.031576
5  ChemBerta             lipo  0.735585        0.006088
2   ChemBart             lipo  0.737041        0.004775
8  ChemLlama             lipo  0.741595        0.005231

In [33]:
utils.calculate_SEM(df_cls_best.groupby(by=['model_type', 'dataset_name'])['metric_1']).sort_values(by=['dataset_name', 'metric_1'], ascending=[True, False])

  model_type         dataset_name  metric_1  standard_error
3  ChemBerta  bace_classification  0.802156        0.003802
0   ChemBart  bace_classification  0.794559        0.008263
6  ChemLlama  bace_classification  0.792156        0.005415
7  ChemLlama                  hiv  0.769427        0.008741
1   ChemBart                  hiv  0.761090        0.004460
4  ChemBerta                  hiv  0.758133        0.007284
8  ChemLlama         tox21_sr_p53  0.789914        0.007250
5  ChemBerta         tox21_sr_p53  0.788588        0.006989
2   ChemBart         tox21_sr_p53  0.788581        0.007211

In [34]:
df_reg_best[df_reg_best['model_type'] == 'ChemBart']

,ft_version,model_mtr_name,model_mtr_ep,dataset_name,dataset_type,metric_1,metric_2,p_value_mantissa,p_value_exponent,epoch,loss,loss_ranking,metric_1_ranking,model_type,model_size,data_size,mts,mtds,msds
0,0,ChemBart_Medium_10m,4,delaney,regression,0.456320,0.357732,7.292727,-37.0,3,0.371624,0,3,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
1,0,ChemBart_Medium_10m,4,lipo,regression,0.721048,0.566975,2.102943,-43.0,6,0.534508,0,1,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
2,0,ChemBart_Medium_10m,6,bace_regression,regression,0.858430,0.718267,1.841017,-23.0,0,0.373197,0,0,ChemBart,Medium,10m,ChemBart_Medium,ChemBart_10m,Medium_10m
3,0,ChemBart_Medium_20m,0,delaney,regression,0.473180,0.379224,7.223428,-40.0,6,0.383850,0,0,ChemBart,Medium,20m,ChemBart_Medium,ChemBart_20m,Medium_20m
4,0,ChemBart_Medium_20m,2,bace_regression,regression,0.815301,0.664588,3.910137,-24.0,3,0.374928,0,0,ChemBart,Medium,20m,ChemBart_Medium,ChemBart_20m,Medium_20m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,4,ChemBart_Small_20m,5,lipo,regression,0.730026,0.568839,1.231096,-43.0,5,0.541574,0,1,ChemBart,Small,20m,ChemBart_Small,ChemBart_20m,Small_20m
230,4,ChemBart_Small_20m,6,delaney,regression,0.465059,0.377089,5.311194,-37.0,6,0.389186,0,2,ChemBart,Small,20m,ChemBart_Small,ChemBart_20m,Small_20m
231,4,ChemBart_Small_30m,1,lipo,regression,0.747914,0.586111,5.925237,-41.0,6,0.546155,0,0,ChemBart,Small,30m,ChemBart_Small,ChemBart_30m,Small_30m
232,4,ChemBart_Small_30m,4,bace_regression,regression,0.858674,0.695968,1.096690,-27.0,1,0.386848,0,4,ChemBart,Small,30m,ChemBart_Small,ChemBart_30m,Small_30m
233,4,ChemBart_Small_30m,6,delaney,regression,0.473569,0.381598,1.063178,-39.0,5,0.363546,0,3,ChemBart,Small,30m,ChemBart_Small,ChemBart_30m,Small_30m

In [35]:
by = 'model_type'
arr_tes_reg_overall = TES_STD_calculator_low_level(well_ordered_df=df_reg_best, is_reg=True, by=by)
arr_tes_cls_overall = TES_STD_calculator_low_level(well_ordered_df=df_cls_best, is_reg=False, by=by)

arr_tes_overall = np.hstack((arr_tes_reg_overall, arr_tes_cls_overall))
tes_lv1 = np.mean(arr_tes_overall, axis=2)
border = arr_tes_overall.shape[1]//2

for idx, mt in enumerate(df_reg[by].unique()):
    print(f"------ {mt} -----")
    # tes
    print(np.sum(tes_lv1[idx]))
    # tes std
    print(np.std(arr_tes_overall[idx]))
    
print("@@@@@ LOW @@@@@@")
print("---- Regression ----")
for idx, mt in enumerate(df_reg[by].unique()):
    print(f"------ {mt} -----")
    # tes
    print(f"{np.sum(tes_lv1[idx][:border]):.6f}")
    # tes std
    print(f"{np.std(arr_tes_overall[idx][:border]):.6f}")

print()
print("---- Classification----")
for idx, mt in enumerate(df_reg[by].unique()):
    print(f"------ {mt} -----")
    # tes
    print(f"{np.sum(tes_lv1[idx][border:]):.6f}")
    # tes std
    print(f"{np.std(arr_tes_overall[idx][border:]):.6f}")

NameError: name 'llist_error_ds' is not defined

# MTDS

In [ ]:
utils.calculate_SEM(df_reg_best.groupby(by=['mtds', 'dataset_name'])['metric_1']).sort_values(by=['dataset_name', 'metric_1'])

In [ ]:
utils.calculate_SEM(df_cls_best.groupby(by=['mtds', 'dataset_name'])['metric_1']).sort_values(by=['dataset_name', 'metric_1'], ascending=[True, False])

In [ ]:
by = 'mtds'
arr_tes_reg = TES_STD_calculator_low_level(well_ordered_df=df_reg_best, is_reg=True, by=by)
arr_tes_cls = TES_STD_calculator_low_level(well_ordered_df=df_cls_best, is_reg=False, by=by)

arr_tes_overall = np.hstack((arr_tes_reg, arr_tes_cls))
tes_lv1 = np.mean(arr_tes_overall, axis=2)
border = arr_tes_overall.shape[1]//2

for idx, mt in enumerate(df_reg[by].unique()):
    print(f"------ {mt} -----")
    # tes
    print(np.sum(tes_lv1[idx]))
    # tes std
    print(np.std(arr_tes_overall[idx]))
    
print("@@@@@ LOW @@@@@@")
print("---- Regression ----")
for idx, mt in enumerate(df_reg[by].unique()):
    print(f"------ {mt} -----")
    # tes
    print(f"{np.sum(tes_lv1[idx][:border]):.6f}")
    # tes std
    print(f"{np.std(arr_tes_overall[idx][:border]):.6f}")

print()
print("---- Classification----")
for idx, mt in enumerate(df_reg[by].unique()):
    print(f"------ {mt} -----")
    # tes
    print(f"{np.sum(tes_lv1[idx][border:]):.6f}")
    # tes std
    print(f"{np.std(arr_tes_overall[idx][border:]):.6f}")

## MTS

In [ ]:
by = 'mts'
arr_tes_reg = TES_STD_calculator_low_level(well_ordered_df=df_reg_best, is_reg=True, by=by)
arr_tes_cls = TES_STD_calculator_low_level(well_ordered_df=df_cls_best, is_reg=False, by=by)

arr_tes_overall = np.hstack((arr_tes_reg, arr_tes_cls))
tes_lv1 = np.mean(arr_tes_overall, axis=2)
border = arr_tes_overall.shape[1]//2

for idx, mt in enumerate(df_reg[by].unique()):
    print(f"------ {mt} -----")
    # tes
    print(np.sum(tes_lv1[idx]))
    # tes std
    print(np.std(arr_tes_overall[idx]))
    
print("@@@@@ LOW @@@@@@")
print("---- Regression ----")
for idx, mt in enumerate(df_reg[by].unique()):
    print(f"------ {mt} -----")
    # tes
    print(f"{np.sum(tes_lv1[idx][:border]):.6f}")
    # tes std
    print(f"{np.std(arr_tes_overall[idx][:border]):.6f}")

print()
print("---- Classification----")
for idx, mt in enumerate(df_reg[by].unique()):
    print(f"------ {mt} -----")
    # tes
    print(f"{np.sum(tes_lv1[idx][border:]):.6f}")
    # tes std
    print(f"{np.std(arr_tes_overall[idx][border:]):.6f}")

## MSDS

In [ ]:
utils.calculate_SEM(df_reg_best.groupby(by=['msds', 'dataset_name'])['metric_1']).sort_values(by=['dataset_name', 'metric_1'])

In [ ]:
utils.calculate_SEM(df_cls_best.groupby(by=['msds', 'dataset_name'])['metric_1']).sort_values(by=['dataset_name', 'metric_1'], ascending=[True, False])

In [ ]:
by = 'msds'
arr_tes_reg = TES_STD_calculator_low_level(well_ordered_df=df_reg_best, is_reg=True, by=by)
arr_tes_cls = TES_STD_calculator_low_level(well_ordered_df=df_cls_best, is_reg=False, by=by)

arr_tes_overall = np.hstack((arr_tes_reg, arr_tes_cls))
tes_lv1 = np.mean(arr_tes_overall, axis=2)
border = arr_tes_overall.shape[1]//2

for idx, mt in enumerate(df_reg[by].unique()):
    print(f"------ {mt} -----")
    # tes
    print(np.sum(tes_lv1[idx]))
    # tes std
    print(np.std(arr_tes_overall[idx]))
    
print("@@@@@ LOW @@@@@@")
print("---- Regression ----")
for idx, mt in enumerate(df_reg[by].unique()):
    print(f"------ {mt} -----")
    # tes
    print(f"{np.sum(tes_lv1[idx][:border]):.6f}")
    # tes std
    print(f"{np.std(arr_tes_overall[idx][:border]):.6f}")

print()
print("---- Classification----")
for idx, mt in enumerate(df_reg[by].unique()):
    print(f"------ {mt} -----")
    # tes
    print(f"{np.sum(tes_lv1[idx][border:]):.6f}")
    # tes std
    print(f"{np.std(arr_tes_overall[idx][border:]):.6f}")